### ISSUE TITLE
Handle image sizing on blog posts

### ISSUE THREAD

**Issue by vavroom** [nicolas-steenhout/main#22]
Find a system to automagically size the images correctly on both the blog landing page and on individual blog posts

**Comment by digilou** [comment]
Are you looking for something like the [eleventy-img plug-in](https://www.11ty.dev/docs/plugins/image/) for picture sizes and adaptable resolution? Or some CSS magic for responsiveness? Or both?

**Comment by vavroom** [comment]
What would you advise/prefer?

I have no strong opinions. 

I want to be able to use images without having to do a lot of heavy lifting of editing them for size before use. And for the sizes to look fine and somewhat responsive. That's the extent of it.
