### ISSUE TITLE
Ideal size for video player?

### ISSUE THREAD

**Issue by vavroom** [nicolas-steenhout/main#24]
The video player has hard coded size in it. Which.... ok?

What size should we aim for to make sure it works? 

```html
<video id="video1" data-able-player preload="auto" width="480" height="360" poster="path_to_image.jpg">
  <source type="video/webm" src="path_to_video.webm" data-desc-src="path_to_described_video.webm"/>
  <source type="video/mp4" src="path_to_video.mp4" data-desc-src="path_to_described_video.mp4"/>
  <track kind="captions" src="path_to_captions.vtt"/>
  <track kind="descriptions" src="path_to_descriptions.vtt"/>
</video>
```

Unless we leave it blank and fits the container as per the [Able Player doc page](https://github.com/ableplayer/ableplayer)?

> width - width of the video player in pixels. This value should reflect the target width of the media itself. If not provided the player will be sized to fit its container. This value is supported for audio as well, but this is not valid HTML so data-width should be used instead.
> data-width - width of the media player in pixels (can be used for either audio or video). If neither width nor data-width are provided, the player will be sized to fit its container.

**Comment by digilou** [comment]
Will check this afternoon. I think it was still responsive, per my CSS, last I checked.
