### ISSUE TITLE
Contrast for menu items

### ISSUE THREAD

**Issue by vavroom** [nicolas-steenhout/main#31]
Just calculated the contrast ratio between the links and background. I get 3:01. Which only just squeezes by as it's large text. 

But my eyes are tired this morning and I was struggling a bit to see them.

How do you feel about making the link text a bit lighter, so the contrast is a bit stronger?

**Comment by digilou** [comment]
It may be the visited link text throwing it. But I will adjust where needed. Contrast it's important but I've rushed the color palette and implementation a bit.

**Comment by vavroom** [comment]
Ahhh, yes, I think you got it - I am looking at the menu now, and the only link I haven't visited is /book. And that one stands out. Good call!

**Comment by digilou** [comment]
On that note, I'm pretty confident dark mode choices may be low. But will address that before completion. If you spy any bad contrast, please do note it so I can tackle it quickly.

**Comment by vavroom** [comment]
If we miss it, I'm pretty sure Alicia will pick up on it. This is the entire idea behind having a non-involved pair of eyes check for us, and keep us honest :D
