### ISSUE TITLE
Past client list and logos

### ISSUE THREAD

**Issue by vavroom** [nicolas-steenhout/main#35]
Get a partial client list and logos. Determine which page is best for it.

**Comment by vavroom** [comment]
@digilou What treatment should I give the logos? Grayscale them? Leave them in their natural colors? What do you think would best fit?

**Comment by digilou** [comment]
@vavroom Grayscale could look nice. Worth a try with CSS `filter`.

**Comment by vavroom** [comment]
Will try CSS filter next
