### ISSUE TITLE
Additional 404 ideas

### ISSUE THREAD

**Issue by digilou** [nicolas-steenhout/main#54]
The picture really makes it! But maybe more enhancement could be made.

* Winston with background removed
* Winston photo turned into sketch-like image
* Thought-bubble around text, as if Winston is saying, "Saawwee"
* Splat image behind Winston

Just spitballing here...

**Comment by digilou** [comment]
@vavroom is this something we need to pursue?

**Comment by vavroom** [comment]
Naaah, let's not worry about it.

Eventually I want to make a better 404 page, including a "search the site" feature, etc. But this is gonna be down the road a ways.
