### ISSUE TITLE
Add an accordion section for transcripts

### ISSUE THREAD

**Issue by vavroom** [nicolas-steenhout/main#72]
Need to have an expand/collapse section for the transcripts on _includes/speaker-reel.html

Ideally it would be something like:
```html
<h3>Transcript</h3>
<div class="transcript">
...
</div>
```
I've tried implementing stuff from [Heydon](https://inclusive-components.design/collapsible-sections/), but it isn't really working for me. Also tried stuff from [Aditus](https://www.aditus.io/patterns/accordion/) which actually seems more on the button for accessibility, but I also can't make it work!

**Comment by shawnthompson** [comment]
Why not use basic HTML and use the 'details' element?

**Comment by vavroom** [comment]
As far as I know, that element is not ready for prime time yet.at least not with screen readers. More testing required. I will do that tomorrow I guess

**Comment by vavroom** [comment]
Went with the `<details>` and `<summary>` after all. Still need some styling to make it look like I want it to look like but that's no rush.
