### ISSUE TITLE
Styling "Book Nic" CTA

### ISSUE THREAD

**Issue by vavroom** [nicolas-steenhout/main#77]
Added a couple instances of "Book Nic" links on the Speaking page. These need to be styled!

I'm thinking something similar to the CTA on https://www.lindaedgecombe.com/speaking-topics/ But not in red. 

I have one set against the light blue/grey, and one set against the dark. I'd like them to be nice and visible. Centered. Rounded corners.

Hope that makes sense :)

**Comment by digilou** [comment]
You mean... like a BUTTON?!? ;)

**Comment by digilou** [comment]
@vavroom You mean... like a BUTTON?!? ;)

**Comment by vavroom** [comment]
No. A button does some thing. A link goes somewhere. And this goes to my contact form! It should look different than the link so it grabs attention. But it should not look like a button, because you interact with a button differently than the link. One uses the spacebar. One uses the return key. But you know that!
