### ISSUE TITLE
Sizing issues - Globals

### ISSUE THREAD

**Issue by vavroom** [nicolas-steenhout/main#80]
◦	When resized (set to dimensions for 1.4.4), “Contact” overflows to expanded container. When set to reflow dimensions, “Podcast” and “Contact” overflow.
◦	In reflow (320x256), you need to scroll in two directions, and some of the text overflows the container, leading to contrast issues.
◦	iOS/Safari – increasing text size makes the page pretty much unreadable
◦	Android/Chrome – not all text resizes. See bug: [https://bugs.chromium.org/p/](https://bugs.chromium.org/p/chromium/issues/detail?id=645717)

**Comment by vavroom** [comment]
![AD41DA32-5674-48A1-AEE1-50346AF855F8_1_102_o](https://github.com/nicolas-steenhout/main/assets/29165258/6694f69b-a9f2-4b1c-a428-46f30da035e6)

This is on Safari/iOS - default size

**Comment by digilou** [comment]
I believe this is stemming from my `grid` layouts that use `minmax()`.

Working on a solution...

**Comment by digilou** [comment]
@vavroom Double-check for me on some of this, since I've made several adjustments.

**Comment by vavroom** [comment]
Can't replicate - seems fixed.
